version: '3'

services:
  healthy-grpc:
    build: ./docker/healthy-grpc
    image: healthy-grpc
    container_name: healthy-grpc
    command: [
      "/healthy-grpc",
      # This value is too short, but for checking behavior about transition of gRPC connection.
      "--max-connection-age", "10s",
    ]
    restart: always
    ports:
      # gRPC
      - "3002:3000"
      # health check gw(http -> gRPC)
      - "3003:3001"
    #logging:
    #  driver: none
