// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/hello.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_860c41a0e7a04411, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Now                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_860c41a0e7a04411, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetNow() *timestamp.Timestamp {
	if m != nil {
		return m.Now
	}
	return nil
}

type MorningRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MorningRequest) Reset()         { *m = MorningRequest{} }
func (m *MorningRequest) String() string { return proto.CompactTextString(m) }
func (*MorningRequest) ProtoMessage()    {}
func (*MorningRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_860c41a0e7a04411, []int{2}
}

func (m *MorningRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MorningRequest.Unmarshal(m, b)
}
func (m *MorningRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MorningRequest.Marshal(b, m, deterministic)
}
func (m *MorningRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MorningRequest.Merge(m, src)
}
func (m *MorningRequest) XXX_Size() int {
	return xxx_messageInfo_MorningRequest.Size(m)
}
func (m *MorningRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MorningRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MorningRequest proto.InternalMessageInfo

func (m *MorningRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MorningReply struct {
	Message              string               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Now                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=now,proto3" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MorningReply) Reset()         { *m = MorningReply{} }
func (m *MorningReply) String() string { return proto.CompactTextString(m) }
func (*MorningReply) ProtoMessage()    {}
func (*MorningReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_860c41a0e7a04411, []int{3}
}

func (m *MorningReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MorningReply.Unmarshal(m, b)
}
func (m *MorningReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MorningReply.Marshal(b, m, deterministic)
}
func (m *MorningReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MorningReply.Merge(m, src)
}
func (m *MorningReply) XXX_Size() int {
	return xxx_messageInfo_MorningReply.Size(m)
}
func (m *MorningReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MorningReply.DiscardUnknown(m)
}

var xxx_messageInfo_MorningReply proto.InternalMessageInfo

func (m *MorningReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MorningReply) GetNow() *timestamp.Timestamp {
	if m != nil {
		return m.Now
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "api.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "api.HelloReply")
	proto.RegisterType((*MorningRequest)(nil), "api.MorningRequest")
	proto.RegisterType((*MorningReply)(nil), "api.MorningReply")
}

func init() { proto.RegisterFile("api/hello.proto", fileDescriptor_860c41a0e7a04411) }

var fileDescriptor_860c41a0e7a04411 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0x2b, 0x56, 0xc7, 0x62, 0xe9, 0x78, 0x59, 0xf6, 0x62, 0x09, 0x1e, 0x7a, 0x90,
	0xac, 0x54, 0xf0, 0x15, 0xf4, 0xe2, 0x65, 0x5b, 0xbc, 0x4f, 0x61, 0x5c, 0x03, 0xd9, 0x4d, 0x4c,
	0x52, 0x24, 0x6f, 0x2f, 0x4d, 0x1b, 0xe9, 0x5e, 0x3c, 0xf5, 0x96, 0xfc, 0x7c, 0xc3, 0x37, 0xff,
	0xc0, 0x94, 0xac, 0xaa, 0xbf, 0x58, 0x6b, 0x23, 0xad, 0x33, 0xc1, 0xe0, 0x88, 0xac, 0xaa, 0xee,
	0x5b, 0x63, 0x5a, 0xcd, 0x75, 0x8a, 0x36, 0xdb, 0xcf, 0x3a, 0xa8, 0x8e, 0x7d, 0xa0, 0xce, 0xee,
	0x29, 0x21, 0x60, 0xf2, 0xb6, 0x1b, 0x6a, 0xf8, 0x7b, 0xcb, 0x3e, 0x20, 0xc2, 0x45, 0x4f, 0x1d,
	0x97, 0xc5, 0xbc, 0x58, 0x5c, 0x37, 0xe9, 0x2d, 0xd6, 0x00, 0x07, 0xc6, 0xea, 0x88, 0x25, 0x8c,
	0x3b, 0xf6, 0x9e, 0xda, 0x0c, 0xe5, 0x2f, 0x3e, 0xc2, 0xa8, 0x37, 0x3f, 0xe5, 0xf9, 0xbc, 0x58,
	0xdc, 0x2c, 0x2b, 0xb9, 0x57, 0xcb, 0xac, 0x96, 0xeb, 0xac, 0x6e, 0x76, 0x98, 0x78, 0x80, 0xdb,
	0x77, 0xe3, 0x7a, 0xd5, 0xb7, 0xff, 0xb9, 0x3f, 0x60, 0xf2, 0x47, 0x9d, 0xd0, 0xbe, 0xf4, 0x30,
	0x7e, 0x75, 0xcc, 0x81, 0x1d, 0x3e, 0xc1, 0xd5, 0x8a, 0x62, 0x6a, 0x88, 0x33, 0x49, 0x56, 0xc9,
	0xe3, 0x8b, 0x54, 0xd3, 0xe3, 0xc8, 0xea, 0x28, 0xce, 0xf0, 0x05, 0x60, 0x45, 0xf1, 0xb0, 0x17,
	0xde, 0x25, 0x60, 0xd8, 0xa5, 0x9a, 0x0d, 0xc3, 0x34, 0xb7, 0xb9, 0x4c, 0xdb, 0x3c, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0xe6, 0xb2, 0xdd, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayMorning(ctx context.Context, in *MorningRequest, opts ...grpc.CallOption) (*MorningReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/api.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayMorning(ctx context.Context, in *MorningRequest, opts ...grpc.CallOption) (*MorningReply, error) {
	out := new(MorningReply)
	err := c.cc.Invoke(ctx, "/api.Greeter/SayMorning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayMorning(context.Context, *MorningRequest) (*MorningReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayMorning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MorningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayMorning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Greeter/SayMorning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayMorning(ctx, req.(*MorningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayMorning",
			Handler:    _Greeter_SayMorning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hello.proto",
}
